# Simple workflow for deploying static content to GitHub Pages
name: Verify if our website is upload

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 0 * * *"
  

jobs:
  check-site:
      runs-on: ubuntu-latest
      steps:
        - name: Check website is up  
          id: health
          run: |
            URL="https://yourusername.github.io/your-repo/"
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
            echo "status=$STATUS" >> $GITHUB_OUTPUT
        #- name: Send Discord alert if down
        #  if: steps.health.outputs.status != '200'
        #  run: |
        #    PAYLOAD='{"content":"Our website is down! Status code: '${{ steps.health.outputs.status }}'"}'
        #    curl -H "Content-Type: application/json" \
        #       -d "$PAYLOAD" \
        #       ${{ secrets.DISCORD_WEBHOOK }}
        - name: Send Discord alert if down
          run: |
            PAYLOAD='{"content":"Do not mind me, I am just a test!"}'
            curl -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               ${{ secrets.DISCORD_WEBHOOK }}